### ISSUE TITLE
[Bug Report] Deprecated option 'envoy.api.v2.listener.Filter.config'

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [erpcya/gRPC-Envoy-Proxy#4]
A message is displayed in the container log indicating

> [2020-02-12 20:27:02.416][6][warning][misc] [source/common/protobuf/utility.cc:441] Using deprecated option 'envoy.api.v2.listener.Filter.config' from file listener_components.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.,

```yaml
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        # deprecated option 'envoy.api.v2.listener.Filter.config' change to 'typed_config'
        config:
          codec_type: auto
          stat_prefix: ingress_htt
```

This must be corrected before it is removed from future versions and the proxy server no longer works with that configuration.
